import { StudentState } from './types';

export const DEFAULT_STATE: StudentState = {
  profile: {
    name: 'Alex Carter',
    college: 'State University',
    major: 'Computer Science',
    gpaGoal: 3.8,
    dailyCalorieGoal: 2400,
    dailyWaterGoal: 2500,
    waterIntake: 1200,
  },
  goals: [
    {
      id: 'g1',
      title: 'Pass Advanced Algorithms with an A grade',
      category: 'academic',
      targetDate: '2026-07-25',
      completed: false,
    },
    {
      id: 'g2',
      title: 'Run a 5K in under 22 minutes',
      category: 'fitness',
      targetDate: '2026-08-10',
      completed: false,
    },
    {
      id: 'g3',
      title: 'Maintain Spring Break savings of $300',
      category: 'financial',
      targetDate: '2026-07-31',
      completed: true,
    },
    {
      id: 'g4',
      title: 'Complete React Life OS project beta',
      category: 'personal',
      targetDate: '2026-07-15',
      completed: false,
    },
  ],
  exams: [
    {
      id: 'ex1',
      course: 'CS 401: Advanced Algorithms',
      title: 'Midterm Exam (Dynamic Programming & Graphs)',
      date: '2026-07-08',
      preparationStatus: 'studying',
    },
    {
      id: 'ex2',
      course: 'CS 320: Database Systems',
      title: 'Final Project Submission & Exam',
      date: '2026-07-13',
      preparationStatus: 'not_started',
    },
  ],
  expenses: [
    {
      id: 'ep1',
      title: 'Campus Bookstore - Reference textbook',
      amount: 65.50,
      category: 'books',
      date: '2026-07-02',
    },
    {
      id: 'ep2',
      title: 'University Diner - Lunch with study group',
      amount: 14.20,
      category: 'food',
      date: '2026-07-04',
    },
    {
      id: 'ep3',
      title: 'Metro Pass monthly reload',
      amount: 45.00,
      category: 'transit',
      date: '2026-07-01',
    },
    {
      id: 'ep4',
      title: 'Blue Bottle - Coffee session',
      amount: 6.75,
      category: 'fun',
      date: '2026-07-05',
    },
  ],
  budget: {
    allowance: 500,
  },
  workouts: [
    {
      id: 'w1',
      title: 'Push Day (Chest, Shoulders, Triceps)',
      completed: true,
      category: 'strength',
      date: '2026-07-05',
    },
    {
      id: 'w2',
      title: 'HIIT Treadmill Run - 25 mins',
      completed: false,
      category: 'cardio',
      date: '2026-07-06',
    },
    {
      id: 'w3',
      title: 'Core Workout & Active Stretch',
      completed: false,
      category: 'yoga',
      date: '2026-07-06',
    },
  ],
  meals: [
    {
      id: 'm1',
      name: 'Oatmeal with Blueberries, Banana & Whey Protein',
      calories: 450,
      type: 'breakfast',
    },
    {
      id: 'm2',
      name: 'Grilled Chicken Breast, Quinoa, and Steamed Broccoli',
      calories: 650,
      type: 'lunch',
    },
    {
      id: 'm3',
      name: 'Protein Shake & Almonds',
      calories: 320,
      type: 'snack',
    },
  ],
  projects: [
    {
      id: 'p1',
      title: 'Distributed Systems Raft Consensus Lab',
      description: 'Implement leader election, log replication, and safety properties in Go.',
      dueDate: '2026-07-15',
      tasks: [
        { id: 'pt1', title: 'Implement basic Leader Election timers', completed: true },
        { id: 'pt2', title: 'Setup heartbeats and client RPC structures', completed: true },
        { id: 'pt3', title: 'Handle log consistency and replication checks', completed: false },
        { id: 'pt4', title: 'Write unit tests for split-brain edge cases', completed: false },
      ],
    },
  ],
  calendar: [
    {
      id: 'c1',
      title: 'CS 401 Lecture',
      startTime: '09:00',
      endTime: '10:30',
      day: 'Monday',
      type: 'class',
    },
    {
      id: 'c2',
      title: 'CS 320 Lecture',
      startTime: '11:00',
      endTime: '12:30',
      day: 'Monday',
      type: 'class',
    },
    {
      id: 'c3',
      title: 'Algorithms Prep Session',
      startTime: '14:00',
      endTime: '16:00',
      day: 'Monday',
      type: 'study',
    },
    {
      id: 'c4',
      title: 'CS 401 Lecture',
      startTime: '09:00',
      endTime: '10:30',
      day: 'Wednesday',
      type: 'class',
    },
    {
      id: 'c5',
      title: 'Gym Workout Block',
      startTime: '17:00',
      endTime: '18:30',
      day: 'Wednesday',
      type: 'personal',
    },
    {
      id: 'c6',
      title: 'CS 320 Group Project Sync',
      startTime: '15:00',
      endTime: '16:30',
      day: 'Thursday',
      type: 'study',
    },
  ],
  emails: [
    {
      id: 'e1',
      sender: 'prof.miller@state.edu',
      subject: 'CS 401 Lecture Notes & Midterm Details',
      snippet: 'Hi Class, I have attached the dynamic programming slide pack. The midterm on Friday will cover everything up to Bellman-Ford...',
      date: '2026-07-05',
      unread: true,
    },
    {
      id: 'e2',
      sender: 'financialaid@state.edu',
      subject: 'Action Required: 2026-2027 Scholarship Disbursement Update',
      snippet: 'Dear Student, your academic scholarship award letter has been updated. Please log in to the student portal and sign...',
      date: '2026-07-03',
      unread: false,
    },
    {
      id: 'e3',
      sender: 'organizers@statehack.io',
      subject: 'StateHack 2026: Team Matching & RSVP Confirmation!',
      snippet: 'Hey Alex! Your spot is confirmed for the 24-hour university hackathon starting next Saturday. Team matching opens in 48 hours...',
      date: '2026-07-05',
      unread: true,
    },
  ],
  files: [
    {
      id: 'f1',
      name: 'CS401_Syllabus.pdf',
      size: '1.4 MB',
      type: 'pdf',
      contentSnippet: 'Syllabus for CS 401 Advanced Algorithms. Course covers: Greedy algorithms, Dynamic Programming, Graph flows, NP-Completeness, Approximation. Midterm weight: 30%, Final weight: 40%, Homeworks: 30%. Office hours: Tuesdays 2-4 PM.',
    },
    {
      id: 'f2',
      name: 'Dynamic_Programming_Slides.pdf',
      size: '4.8 MB',
      type: 'pdf',
      contentSnippet: 'Dynamic Programming (DP): Memoization vs Tabulation. Levenshtein edit distance, Knapsack 0/1 problem, Bellman-Ford shortest path equation: d(v) = min { d(u) + w(u, v) }. Practice problem: Longest Common Subsequence of length N and M.',
    },
  ],
  chatHistory: [
    {
      id: 'ch1',
      sender: 'jarvis',
      text: "Hello Alex! I am Jarvis, your Life OS Assistant. I have indexed your class schedule, upcoming algorithms exam, budget goals, gym workouts, and syllabi PDFs. How can I help you prepare for college success today? You can try asking 'Prepare me for tomorrow' to coordinate your agenda!",
      timestamp: '09:00',
    },
  ],
};
